apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp-pod
  spec:
    containers:
      - command: ['sh','-c','echo Hello K8s && sleep 3600']
        image: busybox
        name: myapp-container
        securityContext:
          privileged: true
    hostPID: true
