apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod2
  labels:
      app: myapp2
  spec:
    hostPID: false
    containers:
    -   name: myapp-container2
        image: busybox2
        command: ['sh','-c','echo Hello K8s && sleep 3600']
        securityContext:
          privileged: true
  volumes:
    - name: dockersock
      hostPath: 
        path: /var/run/docker.sock
