apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  spec:
    containers:
      - command: [ "sh", "-c", "sleep 1h" ]
        image: busybox:1.28
        name: sec-ctx-demo
        securityContext:
          allowPrivilegeEscalation: true
        volumeMounts:
          - mountPath: /data/demo
            name: sec-ctx-vol
    securityContext:
      runAsGroup: 3000
      runAsUser: 1000
    volumes:
      - emptyDir: {}
        name: sec-ctx-vol
