apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
  name: privileged
  spec:
    hostIPC: true
    hostNetwork: true
    hostPID: true
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
         - CAP_NET_RAW
      privileged: true
    volumes:
      - '*'
