apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    name: web
spec:
  containers:
  - command: ["sleep"]
  args: ["999"]
  image: ubuntu:latest
  name: web
  securityContext:
    readOnlyRootFilesystem: false
    volumeMounts:
      - mountPath: /writeable/location/here
      name: volName
  
