apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
  annotations:
    container.apparmor.security.beta.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  capabilities:
    add:
     - CAP_NET_RAW
  volumes:
  - '*'
  hostNetwork: true
  hostIPC: true
  hostPID: true
