apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    name: web
  spec:
    containers:
    - args: ["999"] 
      command: ["sleep"]
      image: ubuntu:latest
      name: web
      securityContext:
        readOnlyRootFilesystem: false
      volumeMounts:
      - mountPath: /writeable/location/here
        name: volName
